Adds wt clone

diff --git a/bin/wt b/bin/wt
--- a/bin/wt
+++ b/bin/wt
@@ -1,23 +1,66 @@
 #!/bin/sh
 
-if [ $# -eq 0 ]; then
+set -e
+
+print_usage () {
 	echo 'Required args not supplied.'
-	echo 'Usage: wt <<add|a> | <remove|rm>>'
-	echo 'Example: wt add, wt a, wt remove, wt rm'
+	echo '\nUsage:\n'
+	echo 'wt <add|a>'
+	echo 'wt <remove|rm>'
+	echo 'wt <clone> <remote-url> [destination]'
 	exit 1
+}
+
+if [ $# -eq 0 ]; then
+	print_usage
 fi
 
-command=$1
-case $command in
+add () {
+	git worktree add $(git branch --list | cut -c 3- | fzf)
+}
+
+remove () {
+	to_remove=$(
+		git worktree list --porcelain | \
+		grep worktree | \
+		cut -c 10- | \
+		fzf
+	)
+	git worktree remove $to_remove 
+	echo "Removed worktree:" $to_remove
+}
+
+clone () {
+	remote_url=$1
+	destination=$2
+	clone_dir=$(echo $(basename $remote_url) | cut -d"." -f1)
+
+	if [ -n "$destination" ]; then
+		clone_dir=$destination
+	fi
+
+	git clone --bare $remote_url $clone_dir
+	git -C $clone_dir worktree add main
+}
+
+action=$1
+case $action in
 	"add"|"a")
-		git worktree add $(git branch --list | cut -c 3- | fzf)
+		add
 		;;
 	"remove"|"rm")
-		git worktree remove $(git worktree list --porcelain | grep worktree | cut -c 10- | fzf)
+		remove
+		;;
+	"clone")
+		if [ $# -lt 2 ]; then
+			echo "Remote URL required."
+			print_usage
+		fi
+		clone $2 $3
 		;;
 	*)
-		echo "Invalid command: $command"
-		exit 1
+		echo "Invalid action: $action"
+		print_usage
 		;;
 esac
 
